#!/bin/bash
# ============================================================
# MetabolicTrack Lab PM — Ubuntu Server 24.04 Setup Script
# Intel N100 Mini PC
# Run once after a fresh Ubuntu Server 24.04 install
# Usage: bash install-ubuntu.sh
# ============================================================

set -e
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}MetabolicTrack Lab PM — Ubuntu Server Setup${NC}"
echo "============================================"

# 1. System update
echo -e "\n${YELLOW}1. Updating system packages...${NC}"
sudo apt update && sudo apt upgrade -y
sudo apt install -y curl git nano ufw python3 python3-pip

# 2. Install Docker
echo -e "\n${YELLOW}2. Installing Docker Engine...${NC}"
if ! command -v docker &> /dev/null; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo usermod -aG docker $USER
    echo -e "${GREEN}Docker installed.${NC}"
else
    echo "Docker already installed — skipping."
fi

# 3. Firewall
echo -e "\n${YELLOW}3. Configuring firewall...${NC}"
sudo ufw allow OpenSSH
sudo ufw allow 80/tcp
sudo ufw --force enable
echo -e "${GREEN}Firewall configured (SSH + HTTP).${NC}"

# 4. Backup directory
mkdir -p ~/backups

# 5. Generate secrets
echo -e "\n${YELLOW}4. Generating secrets for .env...${NC}"
DB_PASSWORD=$(openssl rand -base64 24)
SECRET_KEY=$(openssl rand -hex 32)

pip3 install cryptography --break-system-packages -q 2>/dev/null || true
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || echo "GENERATE_MANUALLY")

# Detect local IP
LOCAL_IP=$(ip route get 1.1.1.1 | grep -oP 'src \K\S+' 2>/dev/null || echo "192.168.1.50")

# Write .env
cd "$(dirname "$0")"
cat > .env << ENVEOF
# MetabolicTrack Lab PM — Environment
# Generated by install-ubuntu.sh on $(date)

DB_PASSWORD=${DB_PASSWORD}
SECRET_KEY=${SECRET_KEY}
FERNET_KEY=${FERNET_KEY}
ANTHROPIC_API_KEY=sk-ant-REPLACE_WITH_YOUR_KEY
ALLOWED_ORIGINS=http://localhost,http://${LOCAL_IP}
ENVEOF

echo -e "${GREEN}.env file created with generated secrets.${NC}"
echo -e "${YELLOW}  → Add your ANTHROPIC_API_KEY to .env before starting${NC}"

# 6. Docker auto-start
echo -e "\n${YELLOW}5. Enabling Docker to start on boot...${NC}"
sudo systemctl enable docker
echo -e "${GREEN}Docker enabled on boot.${NC}"

# 7. Backup cron
echo -e "\n${YELLOW}6. Setting up daily database backup...${NC}"
cat > ~/backup-labpm.sh << 'BKUP'
#!/bin/bash
BACKUP_DIR=~/backups
mkdir -p $BACKUP_DIR
docker exec labpm_db pg_dump -U labpm_user labpm \
  > $BACKUP_DIR/labpm_$(date +%Y%m%d_%H%M%S).sql
find $BACKUP_DIR -name "labpm_*.sql" -mtime +30 -delete
BKUP
chmod +x ~/backup-labpm.sh
(crontab -l 2>/dev/null; echo "0 2 * * * ~/backup-labpm.sh >> ~/backups/backup.log 2>&1") | crontab -
echo -e "${GREEN}Daily backup scheduled at 2:00 AM.${NC}"

# Done
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Add your ANTHROPIC_API_KEY to .env"
echo "     nano .env"
echo ""
echo "  2. Log out and back in (for Docker group to take effect)"
echo "     exit"
echo ""
echo "  3. Start the app:"
echo "     cd ~/labpm-docker && docker compose up -d --build"
echo ""
echo "  4. Access at: http://${LOCAL_IP}"
echo "     Login: cb@metabolictrack.com / ChangeMe!"
echo -e "${GREEN}============================================${NC}"
